---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ceph
    daemon: moncheck
  name: ceph-mon-check
spec:
  replicas: {{ .Values.replicas.mon_check }}
  template:
    metadata:
      name: ceph-mon
      labels:
        app: ceph
        daemon: moncheck
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}      
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: ceph-mon
          image: {{ .Values.images.daemon }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          ports:
            - containerPort: 6789
          env:
            - name: CEPH_DAEMON
              value: MON_HEALTH
            - name: KV_TYPE
              value: k8s
            - name: MON_IP_AUTO_DETECT
              value: "1"
            - name: CLUSTER
              value: ceph
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
          resources:
            requests:
              memory: {{ .Values.resources.mon_check.requests.memory | quote }}
              cpu: {{ .Values.resources.mon_check.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.mon_check.limits.memory | quote }}
              cpu: {{ .Values.resources.mon_check.limits.cpu | quote }}
